### ISSUE TITLE
Compile fails same issue as the others

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/PunchOutDS#1]

**Comment by FluBBaOfWard** [comment]
Pushed.

**Comment by Ntemis** [comment]
/home/demetris/Desktop/Development/ds/PunchOutDS/source/cpu.s:6:10: fatal error: ARM6502/m6502.i: No such file or directory
    6 | #include "ARM6502/m6502.i"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
needs M6502.i

**Comment by Ntemis** [comment]
gtg after #include "ARM6502/M6502.i"

**Comment by FluBBaOfWard** [comment]
Fixed.
